function seqs=configSeqs

seqLOW={
    struct('name','2012LOG15','path','D:\zzz\FSsequences\2012LOG15\img\','startFrame',1,'endFrame',37,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','2012LOG30','path','D:\zzz\FSsequences\2012LOG30\img\','startFrame',1,'endFrame',73,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','badminton1','path','D:\zzz\FSsequences\badminton1\img\','startFrame',1,'endFrame',225,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','disosaur','path','D:\zzz\FSsequences\disosaur\img\','startFrame',1,'endFrame',33,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Djarum','path','D:\zzz\FSsequences\Djarum\img\','startFrame',1,'endFrame',29,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','DJOK10','path','D:\zzz\FSsequences\DJOK10\img\','startFrame',1,'endFrame',70,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','DJOK20','path','D:\zzz\FSsequences\DJOK20\img\','startFrame',1,'endFrame',33,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','hand','path','D:\zzz\FSsequences\hand\img\','startFrame',1,'endFrame',39,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Nadal','path','D:\zzz\FSsequences\Nadal\img\','startFrame',1,'endFrame',29,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','pingpang1','path','D:\zzz\FSsequences\pingpang1\img\','startFrame',1,'endFrame',21,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','pingpang3','path','D:\zzz\FSsequences\pingpang3\img\','startFrame',1,'endFrame',139,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Sharapova10','path','D:\zzz\FSsequences\Sharapova10\img\','startFrame',1,'endFrame',33,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Sharapova15','path','D:\zzz\FSsequences\Sharapova15\img\','startFrame',1,'endFrame',47,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','sphere','path','D:\zzz\FSsequences\sphere\img\','startFrame',1,'endFrame',41,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Tennis10','path','D:\zzz\FSsequences\Tennis10\img\','startFrame',1,'endFrame',73,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Tennis20','path','D:\zzz\FSsequences\Tennis20\img\','startFrame',1,'endFrame',37,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Tennis30','path','D:\zzz\FSsequences\Tennis30\img\','startFrame',1,'endFrame',25,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','UNISYS10','path','D:\zzz\FSsequences\UNISYS10\img\','startFrame',1,'endFrame',110,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','UNISYS20','path','D:\zzz\FSsequences\UNISYS20\img\','startFrame',1,'endFrame',55,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','UNISYS25','path','D:\zzz\FSsequences\UNISYS25\img\','startFrame',1,'endFrame',42,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

seqSudden={struct('name','backboard','path','D:\zzz\FSsequences\backboard\img\','startFrame',1,'endFrame',53,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Ball','path','D:\zzz\FSsequences\Ball\img\','startFrame',1,'endFrame',52,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','billiards1','path','D:\zzz\FSsequences\billiards1\img\','startFrame',1,'endFrame',95,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','billiards2','path','D:\zzz\FSsequences\billiards2\img\','startFrame',1,'endFrame',68,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...    
    struct('name','billiards3','path','D:\zzz\FSsequences\billiards3\img\','startFrame',1,'endFrame',66,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Dribble1','path','D:\zzz\FSsequences\Dribble1\img\','startFrame',1,'endFrame',69,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Dribble2','path','D:\zzz\FSsequences\Dribble2\img\','startFrame',1,'endFrame',91,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Dribble3','path','D:\zzz\FSsequences\Dribble3\img\','startFrame',1,'endFrame',113,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','juggling1','path','D:\zzz\FSsequences\juggling1\img\','startFrame',1,'endFrame',218,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','juggling2','path','D:\zzz\FSsequences\juggling2\img\','startFrame',1,'endFrame',143,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','juggling3','path','D:\zzz\FSsequences\juggling3\img\','startFrame',1,'endFrame',272,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Mulbasketball','path','D:\zzz\FSsequences\Mulbasketball\img\','startFrame',1,'endFrame',299,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','pass','path','D:\zzz\FSsequences\pass\img\','startFrame',1,'endFrame',115,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Rebound','path','D:\zzz\FSsequences\Rebound\img\','startFrame',1,'endFrame',33,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','soccer','path','D:\zzz\FSsequences\soccer\img\','startFrame',1,'endFrame',40,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','TableTennis2','path','D:\zzz\FSsequences\TableTennis2\img\','startFrame',1,'endFrame',160,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Volleyball3','path','D:\zzz\FSsequences\Volleyball3\img\','startFrame',1,'endFrame',156,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

seqCamera={struct('name','Carter','path','D:\zzz\FSsequences\Carter\img\','startFrame',1,'endFrame',799,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','ChoiHongMan','path','D:\zzz\FSsequences\ChoiHongMan\img\','startFrame',1,'endFrame',1458,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fighter','path','D:\zzz\FSsequences\fighter\img\','startFrame',1,'endFrame',217,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','FootballField','path','D:\zzz\FSsequences\FootballField\img\','startFrame',1,'endFrame',1140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Footballman','path','D:\zzz\FSsequences\Footballman\img\','startFrame',1,'endFrame',391,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Griffin','path','D:\zzz\FSsequences\Griffin\img\','startFrame',1,'endFrame',332,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mistakes','path','D:\zzz\FSsequences\mistakes\img\','startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skateboard','path','D:\zzz\FSsequences\skateboard\img\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skating','path','D:\zzz\FSsequences\skating\img\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','spring','path','D:\zzz\FSsequences\spring\img\','startFrame',1,'endFrame',341,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Toycar','path','D:\zzz\FSsequences\Toycar\img\','startFrame',1,'endFrame',195,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','WuLei','path','D:\zzz\FSsequences\WuLei\img\','startFrame',1,'endFrame',329,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','YoungKi','path','D:\zzz\FSsequences\YoungKi\img\','startFrame',1,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
seqs=[seqSudden,seqLOW,seqCamera];